#### Install dependencies:

```{r}
install.packages("RobustLinearReg")
```

---
editor_options: 
  chunk_output_type: console
---

#### Process files:

```{r}
library(RobustLinearReg)
library(ggplot2)
library(ggrepel)

csv_files <- list.files(path="preprocessing_data",pattern = ".*.csv$")
language_data <- read.csv("../data/language_data.csv",sep=";")

language <- c()
family <- c()
tokens <- c()
types <- c()
alpha <- c()
beta <- c()
beta_t <- c()
beta_p <- c()
beta_p_t <- c()

word_labels <- c()

scores_mb_ts <- c()
scores_mb <- c()
scores_mb_ts2 <- c()
scores_mb2 <- c()
scores_mb_ts3 <- c()
scores_mb3 <- c()

charts_data <- data.frame(x = numeric(0), y = numeric(0), Token = character(0), Language = character(0))
charts_predicted_data <- data.frame(x = numeric(0), y = numeric(0), Language = character(0))

charts_data2 <- data.frame(x = numeric(0), y = numeric(0), Token = character(0), Language = character(0))
charts_predicted_data2 <- data.frame(x = numeric(0), y = numeric(0), Language = character(0))

charts_data3 <- data.frame(x = numeric(0), y = numeric(0), Token = character(0), Language = character(0))
charts_predicted_data3 <- data.frame(x = numeric(0), y = numeric(0), Language = character(0))
chart_languages <- c('eu', 'es', 'ko', 'id', 'et', 'kn')

for (file in csv_files) {
  data <- read.csv(paste("preprocessing_data/",file,sep=""))
  
  code <- gsub(".csv", "", file)
  language_info <- language_data[language_data$ISO.code== code,]
  
  language <- c(language, language_info$Language)
  family <- c(family, language_info$Family)
  tokens <- c(tokens, sum(data$Frequency))
  types <- c(types, nrow(data))
  
  ## Frequency <-> rank calculation
  x <- c()
  for (i in seq_along(data$Frequency)) {
    x <- c(x, rep(i, data$Frequency[i]))
  }
  
  # extracting spread x<->y values to calculate score
  frequency <- data$Frequency
  rank <- seq_len(nrow(data))
  y_score <- c(frequency[1])
  x_score <- c(rank[1])
  last_y <- frequency[1]
  space <- min(frequency)+max(frequency)/5
  for (i in 1:length(frequency)) {
    if (last_y>=frequency[i]+space) {
      y_score <- c(y_score, frequency[i])
      x_score <- c(x_score, rank[i])
      last_y <- frequency[i]
    }
  }
  y_score <- log(y_score)
  x_score <- log(x_score)
  
  # Multiplicative binning
  b <- 1.5
  
  binned_x <- c()
  binned_y <- c()
  last_index <- 0
  last_n <- 0
  for (i in seq_along(x)) {
    current_index <- floor(logb(x[i], base=b))
    if (current_index == last_index) {
      last_n <- last_n+1
    } else {
      binned_x <- c(binned_x, sqrt( ( b^last_index ) * ( b^( last_index+1 ) ) ))
      binned_y <- c(binned_y, last_n / ( ( b^( last_index+1 ) ) - ( b^last_index ) ))
      last_n <- 1
      last_index <- current_index
    }
  }
  
  binned_x <- c(binned_x, sqrt( ( b^last_index ) * ( b^( last_index+1 ) ) ))
  binned_y <- c(binned_y, last_n / ( ( b^( last_index+1 ) ) - ( b^last_index ) ))
  
  binned_x <- log(binned_x)
  binned_y <- log(binned_y)
  
  frequency <- log(data$Frequency)
  rank <- log(seq_len(nrow(data)))
  
  x_min <- min(c(rank, binned_x))
  x_max <- max(c(rank, binned_x))
  y_min <- min(c(frequency, binned_y))
  y_max <- max(c(frequency, binned_y))
  
  # Theil-sen method on multiplicative binning data and raw data (all log-log)
  tsmd <- data.frame(x = binned_x, y = binned_y)
  theilsen_model <- theil_sen_regression(x ~ y, data = tsmd)
  theilsen_model_no_mb <- theil_sen_regression(rank ~ frequency)
  
  # Calculate score
  predicted_x <- predict(theilsen_model, newdata = data.frame(y = y_score))
  predicted_x2 <- predict(theilsen_model_no_mb, newdata = data.frame(frequency = y_score))
  score1 <- 0
  score2 <- 0
  for (i in 1:length(x_score)) {
    score1 <- score1+abs(x_score[i]-predicted_x[i])^2
    score2 <- score2+abs(x_score[i]-predicted_x2[i])^2
  }
  scores_mb_ts <- c(scores_mb_ts, sqrt(score1/length(x_score)))
  scores_mb <- c(scores_mb, sqrt(score2/length(x_score)))

  # Prepare data for facet chart + show single chart
  if (code %in% chart_languages) {
    for (i in 1:length(frequency)) {
      charts_data <- rbind(charts_data, data.frame(x = rank[i], y = frequency[i], Token = data$Token[i], Language = language_info$Language))
    }
    
    predicted_y <- c(floor(min(frequency)):ceiling(max(frequency)))
    predicted_x <- predict(theilsen_model, newdata = data.frame(y = predicted_y))
    for (i in 1:length(predicted_y)) {
      charts_predicted_data <- rbind(charts_predicted_data, data.frame(x = predicted_x[i], y = predicted_y[i], Language = language_info$Language))
    }
    
    plot(rank, frequency, type = "p", col = "blue", xlab = "Rank", ylab = "Frequency", main = paste(language_info$Language, "frequencies and rank"), xlim = c(x_min, x_max), ylim = c(y_min, y_max), cex=0.75)
    points(binned_x, binned_y, type = "b", col = "green", cex=0.75)
    abline(theilsen_model,col='red')
    abline(theilsen_model_no_mb,col='purple')
    legend("topright", legend = c("Original", "mb", "Theil-sen", "Theil-sen + mb"), col = c("blue", "green", "purple", "red"), pch = 1)
  }

  alpha <- c(alpha, unname(coef(theilsen_model)[2]))
  
  ## n <-> Frequency calculation
  x <- data$Frequency
  n <- c()
  f <- c()
  
  last_n <- 0
  last_f <- data$Frequency[1]
  for (freq in data$Frequency) {
    if (freq == last_f) {
      last_n <- last_n+1
    } else {
      n <- c(n, last_n)
      f <- c(f, last_f)
      last_n <- 1
      last_f <- freq
    }
  }
  
  n <- c(n, last_n)
  f <- c(f, last_f)
  
  # extracting spread x<->y values to calculate score
  y_score <- c(n[1])
  x_score <- c(f[1])
  last_y <- n[1]
  space <- min(n)+max(n)/5
  for (i in 1:length(n)) {
    if (last_y>=n[i]+space) {
      y_score <- c(y_score, n[i])
      x_score <- c(x_score, f[i])
      last_y <- n[i]
    }
  }
  y_score <- log(y_score)
  x_score <- log(x_score)
  
  n <- log(n)
  f <- log(f)
  
  # Multiplicative binning
  b <- 1.5
  
  binned_x <- c()
  binned_y <- c()
  last_index <- floor(logb(x[1], base=b))
  last_n <- 0
  for (i in seq_along(x)) {
    current_index <- floor(logb(x[i], base=b))
    if (current_index == last_index) {
      last_n <- last_n+1
    } else {
      binned_x <- c(binned_x, sqrt( ( b^last_index ) * ( b^( last_index+1 ) ) ))
      binned_y <- c(binned_y, last_n / ( ( b^( last_index+1 ) ) - ( b^last_index ) ))
      last_n <- 1
      last_index <- current_index
    }
  }
  
  binned_x <- log(c(binned_x, sqrt( ( b^last_index ) * ( b^( last_index+1 ) ) )))
  # adding relatively small amount to avoid negative values while remaining significant
  binned_y <- log(c(binned_y, last_n / ( ( b^( last_index+1 ) ) - ( b^last_index ) ))+1)

  x_min <- min(c(f, binned_x))
  x_max <- max(c(f, binned_x))
  y_min <- min(c(n, binned_y))
  y_max <- max(c(n, binned_y))
  
  # Theil-sen method on multiplicative binning data and raw data (all log-log)
  tsmd <- data.frame(x = binned_x, y = binned_y)
  theilsen_model <- theil_sen_regression(x ~ y, data = tsmd)
  theilsen_model_no_mb <- theil_sen_regression(f ~ n)
  
  beta <- c(beta, unname(coef(theilsen_model)[2]))

  # Calculate score
  predicted_x <- predict(theilsen_model, newdata = data.frame(y = y_score))
  predicted_x2 <- predict(theilsen_model_no_mb, newdata = data.frame(n = y_score))
  score1 <- 0
  score2 <- 0
  for (i in 1:length(x_score)) {
    score1 <- score1+abs(x_score[i]-predicted_x[i])^2
    score2 <- score2+abs(x_score[i]-predicted_x2[i])^2
  }
  scores_mb_ts2 <- c(scores_mb_ts2, sqrt(score1/length(x_score)))
  scores_mb2 <- c(scores_mb2, sqrt(score2/length(x_score)))
  
  # Prepare data for facet chart + show single chart
  if (code %in% chart_languages) {
    for (i in 1:length(f)) {
      charts_data2 <- rbind(charts_data2, data.frame(x = f[i], y = n[i], Token = data$Token[i], Language = language_info$Language))
    }
    
    predicted_y <- c(floor(min(n)):ceiling(max(n)))
    predicted_x <- predict(theilsen_model, newdata = data.frame(y = predicted_y))
    for (i in 1:length(predicted_y)) {
      charts_predicted_data2 <- rbind(charts_predicted_data2, data.frame(x = predicted_x[i], y = predicted_y[i], Language = language_info$Language))
    }
  
    plot(f, n, type = "p", col = "blue", xlab = "Frequency", ylab = "number", main = paste(language_info$Language, "frequencies"), xlim = c(x_min, x_max), ylim = c(y_min, y_max), cex=0.75)
    points(binned_x, binned_y, type = "b", col = "green", cex=0.75)
    abline(theilsen_model,col='red')
    abline(theilsen_model_no_mb,col='purple')
    legend("topright", legend = c("Original", "mb", "Theil-sen", "Theil-sen + mb"), col = c("blue", "green", "purple", "red"), pch = 1)
  }
  
  ## n>= <-> Frequency calculation
  x <- c()
  last_freq <- data$Frequency[1]
  for (i in seq_along(data$Frequency)) {
    if (last_freq != data$Frequency[i]) {
      x <- c(x, rep(last_freq, i))
      last_freq <- data$Frequency[i]
    }
  }
  x <- c(x, rep(last_freq, length(data$Frequency)))
  
  n <- c()
  f <- c()
  
  last_n <- 0
  last_f <- x[1]
  for (freq in x) {
    if (freq == last_f) {
      last_n <- last_n+1
    } else {
      n <- c(n, last_n)
      f <- c(f, last_f)
      last_n <- 1
      last_f <- freq
    }
  }
  
  n <- c(n, last_n)
  f <- c(f, last_f)
  
  # extracting spread x<->y values to calculate score
  y_score <- c(n[1])
  x_score <- c(f[1])
  last_y <- n[1]
  space <- min(n)+max(n)/5
  for (i in 1:length(n)) {
    if (last_y>=n[i]+space) {
      y_score <- c(y_score, n[i])
      x_score <- c(x_score, f[i])
      last_y <- n[i]
    }
  }
  y_score <- log(y_score)
  x_score <- log(x_score)
  
  n <- log(n)
  f <- log(f)
  
  # Multiplicative binning
  b <- 1.5
  
  binned_x <- c()
  binned_y <- c()
  last_index <- floor(logb(x[1], base=b))
  last_n <- 0
  for (i in seq_along(x)) {
    current_index <- floor(logb(x[i], base=b))
    if (current_index == last_index) {
      last_n <- last_n+1
    } else {
      binned_x <- c(binned_x, sqrt( ( b^last_index ) * ( b^( last_index+1 ) ) ))
      binned_y <- c(binned_y, last_n / ( ( b^( last_index+1 ) ) - ( b^last_index ) ))
      last_n <- 1
      last_index <- current_index
    }
  }
  
  binned_x <- log(c(binned_x, sqrt( ( b^last_index ) * ( b^( last_index+1 ) ) )))
  # adding relatively small amount to avoid negative values while remaining significant
  binned_y <- log(c(binned_y, last_n / ( ( b^( last_index+1 ) ) - ( b^last_index ) ))+1)
  
  # Theil-sen method on multiplicative binning data and raw data (all log-log)
  tsmd <- data.frame(x = binned_x, y = binned_y)
  theilsen_model <- theil_sen_regression(x ~ y, data = tsmd)
  theilsen_model_no_mb <- theil_sen_regression(f ~ n)

  beta_p <- c(beta_p, unname(coef(theilsen_model)[2]))
  
  # Calculate score
  predicted_x <- predict(theilsen_model, newdata = data.frame(y = y_score))
  predicted_x2 <- predict(theilsen_model_no_mb, newdata = data.frame(n = y_score))
  score1 <- 0
  score2 <- 0
  for (i in 1:length(x_score)) {
    score1 <- score1+abs(x_score[i]-predicted_x[i])^2
    score2 <- score2+abs(x_score[i]-predicted_x2[i])^2
  }
  scores_mb_ts3 <- c(scores_mb_ts3, sqrt(score1/length(x_score)))
  scores_mb3 <- c(scores_mb3, sqrt(score2/length(x_score)))
  
  x_min <- min(c(f, binned_x))
  x_max <- max(c(f, binned_x))
  y_min <- min(c(n, binned_y))
  y_max <- max(c(n, binned_y))
  
  # Prepare data for facet chart + show single chart
  if (code %in% chart_languages) {
    three_most_frequent <- data$Token[1:5]
    word_labels <- c(word_labels, three_most_frequent)
      
    for (i in 1:length(f)) {
      charts_data3 <- rbind(charts_data3, data.frame(x = f[i], y = n[i], Token = data$Token[i], Language = language_info$Language))
    }
    
    predicted_y <- c(floor(min(n)):ceiling(max(n)))
    predicted_x <- predict(theilsen_model, newdata = data.frame(y = predicted_y))
    for (i in 1:length(predicted_y)) {
      charts_predicted_data3 <- rbind(charts_predicted_data3, data.frame(x = predicted_x[i], y = predicted_y[i], Language = language_info$Language))
    }
    
    plot(f, n, type = "p", col = "blue", xlab = "Frequency", ylab = "number", main = paste(language_info$Language, "<= frequencies"), xlim = c(x_min, x_max), ylim = c(y_min, y_max), cex=0.75)
    points(binned_x, binned_y, type = "b", col = "green", cex=0.75)
    abline(theilsen_model,col='red')
    abline(theilsen_model_no_mb,col='purple')
    legend("topright", legend = c("Original", "mb", "Theil-sen", "Theil-sen + mb"), col = c("blue", "green", "purple", "red"), pch = 1)
  }

  beta_t <- c(beta_t, 1/alpha + 1)
  beta_p_t <- c(beta_p_t, 1/alpha)
}

charts_data_unique <- charts_data[!duplicated(charts_data$Token), ]

# 6 figure plots
p <- ggplot() +
  geom_point(data = charts_data, aes(x = x, y = y)) +
  xlab("Rank") + ylab("Frequency") +
  geom_line(data = charts_predicted_data, aes(x = x, y = y), color = "gray", linetype = "dashed") +
  geom_text_repel(data = subset(charts_data_unique, Token %in% word_labels),
                 aes(x = x, y = y, label = Token), 
                 box.padding = unit(0.2, "lines")) +
  facet_wrap( ~ Language, ncol=3, nrow=2)

print(p)

p <- ggplot() +
  geom_point(data = charts_data2, aes(x = x, y = y)) +
  xlab("Frequency") + ylab("n") +
  geom_line(data = charts_predicted_data2, aes(x = x, y = y), color = "gray", linetype = "dashed") +
  facet_wrap( ~ Language, ncol=3, nrow=2)

print(p)

p <- ggplot() +
  geom_point(data = charts_data3, aes(x = x, y = y)) +
  xlab("Frequency") + ylab("n >=") +
  geom_line(data = charts_predicted_data3, aes(x = x, y = y), color = "gray", linetype = "dashed") +
  facet_wrap( ~ Language, ncol=3, nrow=2)

print(p)

# Print tables in csv format
cat("Language,Family,Tokens,Types,α,β,β′\n")
for (i in seq_along(language)) {
  row <- c(language[i],family[i],tokens[i],types[i],
           format(alpha[i], scientific = FALSE, digits = 4),
           format(beta[i], scientific = FALSE, digits = 4),
           format(beta_p[i], scientific = FALSE, digits = 4))
  cat(paste(row, collapse = ","),"\n")
}
cat("\n\n")

cat("Language,α,β,theoretical β,β′,theoretical β′\n")
for (i in seq_along(language)) {
  row <- c(language[i],
           format(alpha[i], scientific = FALSE, digits = 4),
           format(beta[i], scientific = FALSE, digits = 4),
           format(beta_t[i], scientific = FALSE, digits = 4),
           format(beta_p[i], scientific = FALSE, digits = 4),
           format(beta_p_t[i], scientific = FALSE, digits = 4))
  cat(paste(row, collapse = ","),"\n")
}
cat("\n\n")

# frequency <-> rank scores
cat("Language,score mb+ts,score ts\n")
for (i in seq_along(language)) {
  row <- c(language[i],
           format(scores_mb_ts[i], scientific = FALSE, digits = 4),
           format(scores_mb[i], scientific = FALSE, digits = 4))
  cat(paste(row, collapse = ","),"\n")
}
cat("\n\n")

# n <-> frequency scores
cat("Language,score mb+ts,score ts\n")
for (i in seq_along(language)) {
  row <- c(language[i],
           format(scores_mb_ts2[i], scientific = FALSE, digits = 4),
           format(scores_mb2[i], scientific = FALSE, digits = 4))
  cat(paste(row, collapse = ","),"\n")
}
cat("\n\n")

# n>= <-> frequency scores
cat("Language,score mb+ts,score ts\n")
for (i in seq_along(language)) {
  row <- c(language[i],
           format(scores_mb_ts3[i], scientific = FALSE, digits = 4),
           format(scores_mb3[i], scientific = FALSE, digits = 4))
  cat(paste(row, collapse = ","),"\n")
}
cat("\n")
```
